group: travis_latest
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: pypy3
addons:
  apt:
    packages:
      - libsnappy-dev
install:
  #- pip install python-snappy
  - pip install -e .
  - pip install cffi flake8 nose2 pytest
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  #- pytest test_snappy.py
  - nosetests test_snappy.py
  - if [[ $TRAVIS_PYTHON_VERSION == pypy  ]]; then nosetests test_snappy_cffi.py; fi
